import { Josefin_Sans, Cormorant_Infant } from "next/font/google";
import "./globals.css";
const cormorant = Cormorant_Infant({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-cormorant",
});

const josefin = Josefin_Sans({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-josefin",
});

export const metadata = {
  title: "The TasteEat",
  description: "Generated by create next app - Zihad Hossain Nayem",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${josefin.variable} ${cormorant.variable}`}>
      <body className={cormorant.className}>
        <link
          href="https://fonts.cdnfonts.com/css/cervanttis"
          rel="stylesheet"
        />
        <main>{children}</main>
      </body>
    </html>
  );
}

/* 
tan  #E1B168
clay #292E36
gray #555555
tuna #343942
rose white #FFF8F5
*/
